MongoAdmin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^manage/', include('base.urls')),
    url(r'^admin/', admin.site.urls),
]

base/urls.py
from django.conf.urls import url

from base.views import collection_view, index, db_view, get_csv

urlpatterns = [
    url(r'^$', index),
    url(r'^(?P<db_name>[\w\-.]+)/$', db_view, name='db_view'),
    url(r'^(?P<db_name>[\w\-.]+)/(?P<collection_name>[\w\-.]+)/$', collection_view, name='collection_view'),
    url(r'^(?P<db_name>[\w\-.]+)/(?P<collection_name>[\w\-.]+)/csv$', get_csv, name='get_csv'),
]

base/models.py
import json
import subprocess

from django.conf import settings
from pymongo import MongoClient

TYPES_IGNORED = ['ObjectId']

variety_command = """%s %s --quiet --eval "var collection = '%s', limit = 100, outputFormat='json'" variety.js"""
csv_command = """%sexport --db %s --collection %s --query '%s' --type=csv --fields %s"""

client = MongoClient()


def cache_collection_keys(db_name, collection_name):
    p = subprocess.Popen(variety_command % (settings.MONGO_PATH, db_name, collection_name),
                         shell=True, stdout=subprocess.PIPE)
    variety_result, _ = p.communicate()
    variety_result = json.loads(variety_result.decode('utf8'))
    collection_keys = []
    search_keys = []
    for result in variety_result:
        key = result['_id']['key']
        key_type = list(result['value']['types'].keys())[0]
        if key_type not in TYPES_IGNORED:
            if '.' not in key:
                collection_keys.append((key, key_type))
            if 'XX' not in key:
                search_keys.append((key, key_type))

    client['variety'][db_name].find_one_and_replace(
        {"collection": collection_name},
        {"collection": collection_name, "collection_keys": collection_keys, "search_keys": search_keys},
        upsert=True)


def get_collection_keys(db_name, collection_name):
    cached = client['variety'][db_name].find_one({"collection": collection_name})
    if not cached:
        cache_collection_keys(db_name, collection_name)
        return get_collection_keys(db_name, collection_name)
    return cached["collection_keys"], cached["search_keys"]


def get_collection_csv(db_name, collection_name, fields, query):
    command = csv_command % (settings.MONGO_PATH, db_name, collection_name,
                             json.dumps(query, ensure_ascii=False),
                             ",".join([field[0] for field in fields]))
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
    csv, _ = p.communicate()
    return csv

base/forms.py
from collections import defaultdict

from django import forms

TYPES_NOT_FILTERED = ['Object', 'ObjectId', 'Array']
NUMERIC_TYPES = ['Number', 'NumberLong']
DATE_TYPES = ['Date']


class SearchForm(forms.Form):
    page = forms.IntegerField(initial=1)
    per_page = forms.IntegerField(initial=10)

    def __init__(self, *args, **kwargs):
        self.keys = kwargs.pop("keys")
        super(SearchForm, self).__init__(*args, **kwargs)
        for key, key_type in self.keys:
            if key_type not in TYPES_NOT_FILTERED:
                if key_type in NUMERIC_TYPES:
                    self.fields[key] = forms.IntegerField(required=False)
                elif key_type in DATE_TYPES:
                    self.fields[key + "__gte"] = forms.DateTimeField(required=False)
                    self.fields[key + "__lte"] = forms.DateTimeField(required=False)
                else:
                    self.fields[key] = forms.CharField(required=False)

    def get_result(self, strict=False):
        result = defaultdict(lambda: {})
        for key, key_type in self.keys:
            if key_type not in TYPES_NOT_FILTERED:
                if key_type in DATE_TYPES:
                    if self.cleaned_data[key + "__gte"]:
                        if strict:
                            result[key]["$gte"] = {"$date": self.cleaned_data[key + "__gte"].isoformat()}
                        else:
                            result[key]["$gte"] = self.cleaned_data[key + "__gte"]
                    if self.cleaned_data[key + "__lte"]:
                        if strict:
                            result[key]["$lte"] = {"$date": self.cleaned_data[key + "__lte"].isoformat()}
                        else:
                            result[key]["$lte"] = self.cleaned_data[key + "__lte"]
                elif self.cleaned_data[key]:
                    result[key] = self.cleaned_data[key]
        return result

base/views.py
import codecs

from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404, HttpResponse
from django.shortcuts import render
from pymongo import MongoClient

from base.forms import SearchForm
from base.models import get_collection_keys, get_collection_csv

client = MongoClient()


def index(request):
    objects = []
    for db in client.database_names():
        objects.append({'name': db, 'count': len(client[db].collection_names())})
    return render(request, 'index.html', {'objects': objects})


@staff_member_required
def db_view(request, db_name):
    if db_name not in client.database_names():
        raise Http404()
    objects = []
    db = client[db_name]
    for collection in db.collection_names():
        objects.append({'name': collection, 'count': db[collection].count()})
    return render(request, 'db_view.html', {'objects': objects, 'db_name': db_name})


@staff_member_required
def collection_view(request, db_name, collection_name):
    if db_name not in client.database_names():
        raise Http404()
    db = client[db_name]
    if collection_name not in db.collection_names():
        raise Http404()
    collection = db[collection_name]

    collection_keys, search_keys = get_collection_keys(db_name, collection_name)

    objects = collection.find()

    page = 1
    per_page = 10
    if request.method == 'POST':
        form = SearchForm(data=request.POST, keys=search_keys)
        if form.is_valid():
            query = form.get_result()
            objects = collection.find(query)
            page = form.cleaned_data['page']
            per_page = form.cleaned_data['per_page']
    else:
        form = SearchForm(keys=search_keys)

    paginator = Paginator(objects, per_page)
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    return render(request, 'collection_view.html', {'objects': objects, 'form': form, 'keys': collection_keys})


@staff_member_required
def get_csv(request, db_name, collection_name):
    collection_keys, search_keys = get_collection_keys(db_name, collection_name)
    query = {}
    if request.method == 'POST':
        form = SearchForm(data=request.POST, keys=search_keys)
        if form.is_valid():
            query = form.get_result(strict=True)
    csv = get_collection_csv(db_name, collection_name, collection_keys, query)
    csv = codecs.BOM_UTF8 + csv
    response = HttpResponse(csv, content_type="text/csv; charset=utf-8")
    response['Content-Disposition'] = 'attachment; filename="%s.csv"' % collection_name
    return response

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mongo Admin{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    {% block css %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
            integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
            crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

templates/collection_view.html
{% extends 'base.html' %}
{% load bootstrap getattr %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".page-link").click(function () {
                $("#id_page").val($(this).data("page-number"));
                $("#search-form").submit();
                return false;
            });
        });
    </script>
{% endblock %}

{% block body %}
    <div class="col-lg-12">
        <form method="post" id="search-form">
            {% csrf_token %}
            <input type="hidden" name="page" value="{{ objects.number }}" id="page_number">
            <div class="col-lg-12 col-md-12 col-sm-12 clearfix">
                {% for field in form.visible_fields %}
                    <div class="col-lg-3 col-md-5 col-sm-10" style="float: left">
                        {{ field|bootstrap }}
                    </div>
                {% endfor %}

            </div>
            <button type="submit" style="width: 48%" class="btn btn-primary">find</button>
            <button type="submit" formaction="csv" style="width: 48%" class="btn btn-info">CSV</button>
        </form>
    </div>
    <hr/>
    <div class="col-lg-12">
        {% include 'pagination_template.html' %}
        <table class="table-striped table-hover w-100" style="margin-bottom: 16px">
            <thead>
            <tr>
                {% for key in keys %}
                    <th>{{ key.0 }}<br/>{{ key.1 }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for obj in objects %}
                <tr>
                    {% for key in keys %}
                        <td>{{ obj|getattr:key.0 }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'pagination_template.html' %}
    </div>
{% endblock %}

templates/db_view.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-lg-12">
        <table class="table-striped table-hover w-100">
            <thead>
            <tr>
                <th>name</th>
                <th>size</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in objects %}
                <tr>
                    <td>
                        <a href="{% url 'collection_view' db_name=db_name collection_name=obj.name %}">
                            {{ obj.name }}
                        </a>
                    </td>
                    <td>{{ obj.count }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-lg-12">
        <table class="table-striped table-hover w-100">
            <thead>
            <tr>
                <th>name</th>
                <th>size</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in objects %}
                <tr>
                    <td>
                        <a href="{% url 'db_view' db_name=obj.name %}">
                            {{ obj.name }}
                        </a>
                    </td>
                    <td>{{ obj.count }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/pagination_template.html
<div class="col-lg-12" style="text-align: center">
    <nav aria-label="Page navigation" style="display: inline-block">
        <ul class="pagination">
            {% if objects.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="#" data-page-number="1"><<</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#" data-page-number="{{ objects.previous_page_number }}"><</a>
                </li>
            {% endif %}
            <li class="page-item">
                <a class="page-link" href="#" data-page-number="{{ objects.number }}">
                    {{ objects.number }} of {{ objects.paginator.num_pages }}
                </a>
            </li>
            {% if objects.has_next %}
                <li class="page-item">
                    <a class="page-link" href="#" data-page-number="{{ objects.next_page_number }}">></a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#" data-page-number="{{ objects.paginator.num_pages }}">>></a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>